import { SaleRecord } from '../types/sales';
import { calculateSaleTotals } from './calculations';

export function getDemoSalesData(): SaleRecord[] {
  const rawList: Array<{
    invoiceNumber: string;
    dayOffset: number; // days before today
    customerName: string;
    customerEmail: string;
    customerPhone: string;
    productName: string;
    category: string;
    quantity: number;
    unitPrice: number;
    discount: number;
    tax: number;
    paymentMethod: 'UPI' | 'Card' | 'Bank Transfer' | 'Cash' | 'Other';
    salesPerson: string;
    region: 'North' | 'South' | 'East' | 'West' | 'Central';
    status: 'Completed' | 'Pending' | 'Cancelled' | 'Processing';
    notes: string;
  }> = [
    {
      invoiceNumber: 'INV-2026-0101',
      dayOffset: 0, // today
      customerName: 'Aarav Singhania',
      customerEmail: 'aarav.singh@techcorp.in',
      customerPhone: '+91 98201 44521',
      productName: 'MacBook Pro 16" M3 Max',
      category: 'Electronics',
      quantity: 2,
      unitPrice: 249900,
      discount: 5,
      tax: 18,
      paymentMethod: 'Bank Transfer',
      salesPerson: 'Nitish Kumar',
      region: 'West',
      status: 'Completed',
      notes: 'Corporate procurement for senior engineering leads.',
    },
    {
      invoiceNumber: 'INV-2026-0102',
      dayOffset: 0, // today
      customerName: 'Priya Sharma',
      customerEmail: 'priya.sharma@innovate.co',
      customerPhone: '+91 98450 12890',
      productName: 'SalesFlow Pro Enterprise 1-Yr',
      category: 'Software',
      quantity: 5,
      unitPrice: 35000,
      discount: 10,
      tax: 18,
      paymentMethod: 'UPI',
      salesPerson: 'Meera Joshi',
      region: 'South',
      status: 'Completed',
      notes: '5 team seat licenses with priority SLA support.',
    },
    {
      invoiceNumber: 'INV-2026-0103',
      dayOffset: 1, // yesterday
      customerName: 'Vikramaditya Verma',
      customerEmail: 'vikram.verma@delhicapital.org',
      customerPhone: '+91 99100 87341',
      productName: 'Dell UltraSharp 32" 4K Thunderbolt',
      category: 'Hardware',
      quantity: 4,
      unitPrice: 84500,
      discount: 8,
      tax: 18,
      paymentMethod: 'Card',
      salesPerson: 'Rohan Gupta',
      region: 'North',
      status: 'Completed',
      notes: 'Delivered to Okhla Phase 3 office.',
    },
    {
      invoiceNumber: 'INV-2026-0104',
      dayOffset: 1,
      customerName: 'Ananya Deshmukh',
      customerEmail: 'ananya.d@mumbaistudios.com',
      customerPhone: '+91 98212 90123',
      productName: 'Sony WH-1000XM5 Studio Headset',
      category: 'Accessories',
      quantity: 3,
      unitPrice: 28990,
      discount: 12,
      tax: 18,
      paymentMethod: 'UPI',
      salesPerson: 'Nitish Kumar',
      region: 'West',
      status: 'Completed',
      notes: 'Sound design department upgrade.',
    },
    {
      invoiceNumber: 'INV-2026-0105',
      dayOffset: 2,
      customerName: 'Arjun Kulkarni',
      customerEmail: 'arjun.k@fintechcloud.in',
      customerPhone: '+91 97654 33120',
      productName: 'Keychron Q1 Pro Mechanical Keyboard',
      category: 'Accessories',
      quantity: 6,
      unitPrice: 16500,
      discount: 5,
      tax: 18,
      paymentMethod: 'UPI',
      salesPerson: 'Divya Nair',
      region: 'West',
      status: 'Completed',
      notes: 'Special tactile brown switches requested.',
    },
    {
      invoiceNumber: 'INV-2026-0106',
      dayOffset: 3,
      customerName: 'Sunita Chaudhuri',
      customerEmail: 'sunita.c@bengalexports.com',
      customerPhone: '+91 98300 76541',
      productName: 'Cloud Migration & Security SLA',
      category: 'Services',
      quantity: 1,
      unitPrice: 185000,
      discount: 15,
      tax: 18,
      paymentMethod: 'Bank Transfer',
      salesPerson: 'Arjun Kapoor',
      region: 'East',
      status: 'Processing',
      notes: 'Initial milestone payment completed.',
    },
    {
      invoiceNumber: 'INV-2026-0107',
      dayOffset: 4,
      customerName: 'Gaurav Narang',
      customerEmail: 'gaurav@naranglogistics.in',
      customerPhone: '+91 98111 65432',
      productName: 'Herman Miller Aeron Ergonomic Chair',
      category: 'Furniture',
      quantity: 2,
      unitPrice: 115000,
      discount: 10,
      tax: 18,
      paymentMethod: 'Card',
      salesPerson: 'Rohan Gupta',
      region: 'North',
      status: 'Completed',
      notes: 'Graphite frame with PostureFit SL.',
    },
    {
      invoiceNumber: 'INV-2026-0108',
      dayOffset: 5,
      customerName: 'Kavita Menon',
      customerEmail: 'kavita.m@kochipharma.com',
      customerPhone: '+91 94470 11982',
      productName: 'iPad Pro 13" M4 512GB',
      category: 'Electronics',
      quantity: 3,
      unitPrice: 139900,
      discount: 4,
      tax: 18,
      paymentMethod: 'Bank Transfer',
      salesPerson: 'Meera Joshi',
      region: 'South',
      status: 'Completed',
      notes: 'Tablets for regional medical field representatives.',
    },
    {
      invoiceNumber: 'INV-2026-0109',
      dayOffset: 6,
      customerName: 'Manish Agarwal',
      customerEmail: 'manish@agarwalgems.com',
      customerPhone: '+91 94140 23891',
      productName: 'Anker Prime 200W GaN Charging Hub',
      category: 'Accessories',
      quantity: 10,
      unitPrice: 11999,
      discount: 8,
      tax: 18,
      paymentMethod: 'UPI',
      salesPerson: 'Rohan Gupta',
      region: 'North',
      status: 'Completed',
      notes: 'Bulk purchase for showroom executive desks.',
    },
    {
      invoiceNumber: 'INV-2026-0110',
      dayOffset: 8,
      customerName: 'Neha Sundaram',
      customerEmail: 'neha.s@chennaibio.in',
      customerPhone: '+91 98401 55678',
      productName: 'Logitech MX Master 3S Wireless Mouse',
      category: 'Accessories',
      quantity: 8,
      unitPrice: 9495,
      discount: 6,
      tax: 18,
      paymentMethod: 'Card',
      salesPerson: 'Divya Nair',
      region: 'South',
      status: 'Completed',
      notes: 'Quiet click ergonomic setup.',
    },
    {
      invoiceNumber: 'INV-2026-0111',
      dayOffset: 10,
      customerName: 'Harsh Vardhan',
      customerEmail: 'harsh.v@hyderabadventures.io',
      customerPhone: '+91 99890 33451',
      productName: 'ErgoLift Dual-Motor Standing Desk',
      category: 'Furniture',
      quantity: 4,
      unitPrice: 42500,
      discount: 12,
      tax: 18,
      paymentMethod: 'Bank Transfer',
      salesPerson: 'Meera Joshi',
      region: 'South',
      status: 'Completed',
      notes: 'Walnut solid wood top with anti-collision.',
    },
    {
      invoiceNumber: 'INV-2026-0112',
      dayOffset: 12,
      customerName: 'Rameshwar Reddy',
      customerEmail: 'ramesh.r@vizagmetals.co',
      customerPhone: '+91 98480 99812',
      productName: 'CalDigit TS4 Thunderbolt 4 Dock',
      category: 'Hardware',
      quantity: 5,
      unitPrice: 38500,
      discount: 7,
      tax: 18,
      paymentMethod: 'Card',
      salesPerson: 'Divya Nair',
      region: 'South',
      status: 'Pending',
      notes: 'Waiting for international customs batch clearance.',
    },
    {
      invoiceNumber: 'INV-2026-0113',
      dayOffset: 14,
      customerName: 'Pooja Bhattacharya',
      customerEmail: 'pooja.b@kolkatadesign.in',
      customerPhone: '+91 98311 22459',
      productName: 'SalesFlow Pro Starter License',
      category: 'Software',
      quantity: 2,
      unitPrice: 18000,
      discount: 0,
      tax: 18,
      paymentMethod: 'UPI',
      salesPerson: 'Arjun Kapoor',
      region: 'East',
      status: 'Completed',
      notes: 'Quick onboarding demo completed.',
    },
    {
      invoiceNumber: 'INV-2026-0114',
      dayOffset: 16,
      customerName: 'Chetan Parekh',
      customerEmail: 'chetan@ahmedabadchem.com',
      customerPhone: '+91 98250 88912',
      productName: 'MacBook Air 15" M3 16GB',
      category: 'Electronics',
      quantity: 4,
      unitPrice: 134900,
      discount: 7,
      tax: 18,
      paymentMethod: 'Bank Transfer',
      salesPerson: 'Nitish Kumar',
      region: 'West',
      status: 'Completed',
      notes: 'Starlight finish with AppleCare warranty included.',
    },
    {
      invoiceNumber: 'INV-2026-0115',
      dayOffset: 18,
      customerName: 'Bhavna Chawla',
      customerEmail: 'bhavna.c@chandigarhretail.in',
      customerPhone: '+91 98760 14523',
      productName: 'POS Thermal Receipt Printer Pro',
      category: 'Hardware',
      quantity: 6,
      unitPrice: 14200,
      discount: 10,
      tax: 18,
      paymentMethod: 'Cash',
      salesPerson: 'Rohan Gupta',
      region: 'North',
      status: 'Completed',
      notes: 'Cash invoice receipt verified at retail branch counter.',
    },
    {
      invoiceNumber: 'INV-2026-0116',
      dayOffset: 20,
      customerName: 'Sanjay Toshniwal',
      customerEmail: 'sanjay@indoretextiles.com',
      customerPhone: '+91 94250 67123',
      productName: 'ERP Data Integration Consulting',
      category: 'Services',
      quantity: 1,
      unitPrice: 145000,
      discount: 10,
      tax: 18,
      paymentMethod: 'Bank Transfer',
      salesPerson: 'Arjun Kapoor',
      region: 'Central',
      status: 'Completed',
      notes: 'Completed warehouse sync script implementation.',
    },
    {
      invoiceNumber: 'INV-2026-0117',
      dayOffset: 22,
      customerName: 'Tarun Bhatia',
      customerEmail: 'tarun.bhatia@gurgaonadvisors.com',
      customerPhone: '+91 99990 12345',
      productName: 'Dell UltraSharp 32" 4K Thunderbolt',
      category: 'Hardware',
      quantity: 2,
      unitPrice: 84500,
      discount: 5,
      tax: 18,
      paymentMethod: 'Card',
      salesPerson: 'Rohan Gupta',
      region: 'North',
      status: 'Completed',
      notes: 'Finance director workstation equipment.',
    },
    {
      invoiceNumber: 'INV-2026-0118',
      dayOffset: 25,
      customerName: 'Meenakshi Sundaresan',
      customerEmail: 'meenakshi@maduraitech.edu.in',
      customerPhone: '+91 94430 78901',
      productName: 'Sony WH-1000XM5 Studio Headset',
      category: 'Accessories',
      quantity: 4,
      unitPrice: 28990,
      discount: 10,
      tax: 18,
      paymentMethod: 'UPI',
      salesPerson: 'Divya Nair',
      region: 'South',
      status: 'Completed',
      notes: 'Language learning laboratory acquisition.',
    },
    {
      invoiceNumber: 'INV-2026-0119',
      dayOffset: 28,
      customerName: 'Deepak Joshi',
      customerEmail: 'deepak.joshi@puneauto.co',
      customerPhone: '+91 98220 34567',
      productName: 'ErgoLift Dual-Motor Standing Desk',
      category: 'Furniture',
      quantity: 3,
      unitPrice: 42500,
      discount: 8,
      tax: 18,
      paymentMethod: 'Card',
      salesPerson: 'Nitish Kumar',
      region: 'West',
      status: 'Completed',
      notes: 'Shipped to Hinjewadi Phase 1 R&D Center.',
    },
    {
      invoiceNumber: 'INV-2026-0120',
      dayOffset: 32,
      customerName: 'Rohit Aggarwal',
      customerEmail: 'rohit@ludhianamachines.com',
      customerPhone: '+91 98140 55678',
      productName: 'SalesFlow Pro Enterprise 1-Yr',
      category: 'Software',
      quantity: 3,
      unitPrice: 35000,
      discount: 15,
      tax: 18,
      paymentMethod: 'Bank Transfer',
      salesPerson: 'Rohan Gupta',
      region: 'North',
      status: 'Completed',
      notes: 'Includes customized export templates.',
    },
    {
      invoiceNumber: 'INV-2026-0121',
      dayOffset: 35,
      customerName: 'Shalini Murthy',
      customerEmail: 'shalini@bengalurulabs.org',
      customerPhone: '+91 98455 67890',
      productName: 'MacBook Pro 16" M3 Max',
      category: 'Electronics',
      quantity: 1,
      unitPrice: 249900,
      discount: 0,
      tax: 18,
      paymentMethod: 'Card',
      salesPerson: 'Meera Joshi',
      region: 'South',
      status: 'Completed',
      notes: '64GB Unified Memory model for AI research.',
    },
    {
      invoiceNumber: 'INV-2026-0122',
      dayOffset: 40,
      customerName: 'Kunal Singhal',
      customerEmail: 'kunal.s@noidamedia.in',
      customerPhone: '+91 99580 23412',
      productName: 'Logitech MX Master 3S Wireless Mouse',
      category: 'Accessories',
      quantity: 5,
      unitPrice: 9495,
      discount: 5,
      tax: 18,
      paymentMethod: 'UPI',
      salesPerson: 'Rohan Gupta',
      region: 'North',
      status: 'Completed',
      notes: 'Video editing suite peripherals.',
    },
    {
      invoiceNumber: 'INV-2026-0123',
      dayOffset: 45,
      customerName: 'Nandini Sen',
      customerEmail: 'nandini@howrahshipping.com',
      customerPhone: '+91 98305 67123',
      productName: 'CalDigit TS4 Thunderbolt 4 Dock',
      category: 'Hardware',
      quantity: 2,
      unitPrice: 38500,
      discount: 5,
      tax: 18,
      paymentMethod: 'Bank Transfer',
      salesPerson: 'Arjun Kapoor',
      region: 'East',
      status: 'Completed',
      notes: 'Dual 4K display connectivity requirement.',
    },
    {
      invoiceNumber: 'INV-2026-0124',
      dayOffset: 50,
      customerName: 'Varun Somani',
      customerEmail: 'varun@jaipurjewels.net',
      customerPhone: '+91 94141 89012',
      productName: 'Herman Miller Aeron Ergonomic Chair',
      category: 'Furniture',
      quantity: 1,
      unitPrice: 115000,
      discount: 10,
      tax: 18,
      paymentMethod: 'UPI',
      salesPerson: 'Rohan Gupta',
      region: 'North',
      status: 'Completed',
      notes: 'Mineral white colorway customized.',
    },
    {
      invoiceNumber: 'INV-2026-0125',
      dayOffset: 55,
      customerName: 'Swati Pillai',
      customerEmail: 'swati.p@trivandrumhealth.org',
      customerPhone: '+91 94471 23456',
      productName: 'Cloud Migration & Security SLA',
      category: 'Services',
      quantity: 1,
      unitPrice: 185000,
      discount: 12,
      tax: 18,
      paymentMethod: 'Bank Transfer',
      salesPerson: 'Divya Nair',
      region: 'South',
      status: 'Completed',
      notes: 'HIPAA compliance audit checklist signed.',
    },
    {
      invoiceNumber: 'INV-2026-0126',
      dayOffset: 60,
      customerName: 'Yashwant Rathi',
      customerEmail: 'yash@nagpuroranges.biz',
      customerPhone: '+91 98230 45678',
      productName: 'POS Thermal Receipt Printer Pro',
      category: 'Hardware',
      quantity: 4,
      unitPrice: 14200,
      discount: 8,
      tax: 18,
      paymentMethod: 'Cash',
      salesPerson: 'Arjun Kapoor',
      region: 'Central',
      status: 'Completed',
      notes: 'Cold storage gate dispatch counter units.',
    },
    {
      invoiceNumber: 'INV-2026-0127',
      dayOffset: 65,
      customerName: 'Alok Mukherjee',
      customerEmail: 'alok.m@bhubaneswaranalytics.in',
      customerPhone: '+91 94370 12987',
      productName: 'SalesFlow Pro Starter License',
      category: 'Software',
      quantity: 4,
      unitPrice: 18000,
      discount: 10,
      tax: 18,
      paymentMethod: 'UPI',
      salesPerson: 'Arjun Kapoor',
      region: 'East',
      status: 'Completed',
      notes: 'Annual recurring subscription setup.',
    },
    {
      invoiceNumber: 'INV-2026-0128',
      dayOffset: 70,
      customerName: 'Divya Rastogi',
      customerEmail: 'divya.r@lucknowcrafts.co',
      customerPhone: '+91 94150 98765',
      productName: 'iPad Pro 13" M4 512GB',
      category: 'Electronics',
      quantity: 2,
      unitPrice: 139900,
      discount: 5,
      tax: 18,
      paymentMethod: 'Card',
      salesPerson: 'Rohan Gupta',
      region: 'North',
      status: 'Cancelled',
      notes: 'Customer altered procurement specifications prior to dispatch.',
    },
    {
      invoiceNumber: 'INV-2026-0129',
      dayOffset: 75,
      customerName: 'Aditya Birla Associate',
      customerEmail: 'aditya.grp@mumbaicorporate.com',
      customerPhone: '+91 98200 11223',
      productName: 'ERP Data Integration Consulting',
      category: 'Services',
      quantity: 2,
      unitPrice: 145000,
      discount: 15,
      tax: 18,
      paymentMethod: 'Bank Transfer',
      salesPerson: 'Nitish Kumar',
      region: 'West',
      status: 'Completed',
      notes: 'Full database migration phase completed.',
    },
    {
      invoiceNumber: 'INV-2026-0130',
      dayOffset: 80,
      customerName: 'Suresh Nambiar',
      customerEmail: 'suresh@calicutspices.in',
      customerPhone: '+91 94460 33211',
      productName: 'Keychron Q1 Pro Mechanical Keyboard',
      category: 'Accessories',
      quantity: 4,
      unitPrice: 16500,
      discount: 5,
      tax: 18,
      paymentMethod: 'UPI',
      salesPerson: 'Meera Joshi',
      region: 'South',
      status: 'Completed',
      notes: 'Custom keycaps ordered for logistics office.',
    },
    {
      invoiceNumber: 'INV-2026-0131',
      dayOffset: 85,
      customerName: 'Vinod Kanetkar',
      customerEmail: 'vinod@nashikwines.co.in',
      customerPhone: '+91 98221 44556',
      productName: 'Anker Prime 200W GaN Charging Hub',
      category: 'Accessories',
      quantity: 5,
      unitPrice: 11999,
      discount: 10,
      tax: 18,
      paymentMethod: 'Card',
      salesPerson: 'Nitish Kumar',
      region: 'West',
      status: 'Completed',
      notes: 'Visitor conference room power hubs.',
    },
    {
      invoiceNumber: 'INV-2026-0132',
      dayOffset: 90,
      customerName: 'Simran Walia',
      customerEmail: 'simran.w@amritsargrains.com',
      customerPhone: '+91 98150 99123',
      productName: 'MacBook Air 15" M3 16GB',
      category: 'Electronics',
      quantity: 2,
      unitPrice: 134900,
      discount: 5,
      tax: 18,
      paymentMethod: 'Bank Transfer',
      salesPerson: 'Rohan Gupta',
      region: 'North',
      status: 'Completed',
      notes: 'Field auditor workstations.',
    },
    {
      invoiceNumber: 'INV-2026-0133',
      dayOffset: 95,
      customerName: 'Prateek Goel',
      customerEmail: 'prateek.g@ghaziabadsteel.in',
      customerPhone: '+91 98109 87654',
      productName: 'Dell UltraSharp 32" 4K Thunderbolt',
      category: 'Hardware',
      quantity: 3,
      unitPrice: 84500,
      discount: 6,
      tax: 18,
      paymentMethod: 'Card',
      salesPerson: 'Rohan Gupta',
      region: 'North',
      status: 'Completed',
      notes: 'Design team CAD stations.',
    },
    {
      invoiceNumber: 'INV-2026-0134',
      dayOffset: 100,
      customerName: 'Leela Venkatesh',
      customerEmail: 'leela.v@coimbatoretextiles.com',
      customerPhone: '+91 94420 54321',
      productName: 'SalesFlow Pro Enterprise 1-Yr',
      category: 'Software',
      quantity: 4,
      unitPrice: 35000,
      discount: 12,
      tax: 18,
      paymentMethod: 'UPI',
      salesPerson: 'Divya Nair',
      region: 'South',
      status: 'Completed',
      notes: 'Textile distribution unit tracking.',
    },
    {
      invoiceNumber: 'INV-2026-0135',
      dayOffset: 110,
      customerName: 'Bhaskar Roy',
      customerEmail: 'bhaskar.roy@siliguritea.in',
      customerPhone: '+91 94340 11223',
      productName: 'Sony WH-1000XM5 Studio Headset',
      category: 'Accessories',
      quantity: 2,
      unitPrice: 28990,
      discount: 5,
      tax: 18,
      paymentMethod: 'Card',
      salesPerson: 'Arjun Kapoor',
      region: 'East',
      status: 'Completed',
      notes: 'Executive travel audio equipment.',
    }
  ];

  const now = new Date();

  return rawList.map((item, index) => {
    const targetDate = new Date(now.getTime() - item.dayOffset * 24 * 60 * 60 * 1000);
    const dateStr = targetDate.toISOString().split('T')[0];
    const totals = calculateSaleTotals(item.quantity, item.unitPrice, item.discount, item.tax);

    return {
      id: `demo-${index + 1}-${Date.now().toString(36)}`,
      invoiceNumber: item.invoiceNumber,
      saleDate: dateStr,
      customerName: item.customerName,
      customerEmail: item.customerEmail,
      customerPhone: item.customerPhone,
      productName: item.productName,
      category: item.category,
      quantity: item.quantity,
      unitPrice: item.unitPrice,
      discount: item.discount,
      tax: item.tax,
      subtotal: totals.subtotal,
      discountAmount: totals.discountAmount,
      taxAmount: totals.taxAmount,
      totalAmount: totals.totalAmount,
      paymentMethod: item.paymentMethod,
      salesPerson: item.salesPerson,
      region: item.region,
      status: item.status,
      notes: item.notes,
      createdAt: targetDate.toISOString(),
      updatedAt: targetDate.toISOString(),
    };
  });
}
